services:
  lomseb_api:
    container_name: lomseb_api
    image: lomseb_api
    restart: unless-stopped
    build: .
    networks: 
      - nginxproxymanager_default
    env_file:
      - .env
  
    ports:
      - "3550:5000"
    command: ["node", "app.js"]
  
networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true

